# Generated by Django 6.0.2 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="submission_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="supporting_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
