# Generated by Django 6.0.2 on 2026-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(default='2026-02-20 23:59:00', help_text='Submission deadline'),
            preserve_default=False,
        ),
    ]
