# Generated by Django 6.0.2 on 2026-02-20
from django.db import migrations, models


def _rename_post_group_column_forward(apps, schema_editor):
    connection = schema_editor.connection
    table_name = "myapp_post"

    with connection.cursor() as cursor:
        table_names = connection.introspection.table_names(cursor)
        if table_name not in table_names:
            return

        columns = [
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        ]

    if "max_student_per_group" in columns and "max_students_per_group" not in columns:
        schema_editor.execute(
            "ALTER TABLE myapp_post RENAME COLUMN max_student_per_group TO max_students_per_group;"
        )


def _rename_post_group_column_backward(apps, schema_editor):
    connection = schema_editor.connection
    table_name = "myapp_post"

    with connection.cursor() as cursor:
        table_names = connection.introspection.table_names(cursor)
        if table_name not in table_names:
            return

        columns = [
            column.name
            for column in connection.introspection.get_table_description(cursor, table_name)
        ]

    if "max_students_per_group" in columns and "max_student_per_group" not in columns:
        schema_editor.execute(
            "ALTER TABLE myapp_post RENAME COLUMN max_students_per_group TO max_student_per_group;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_post_deadline"),
    ]

    operations = [
        migrations.RunPython(
            _rename_post_group_column_forward,
            _rename_post_group_column_backward,
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("lecturer", "Lecturer")],
                default="student",
                max_length=20,
            ),
        ),
    ]
