# Generated by Django 6.0.2 on 2026-02-20
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_backfill_empty_profile_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="myapp.course",
            ),
        ),
    ]
